[workspace]
members = [
    "arduino_script",
    "windows_interface",
]

[profile.dev-arduino]
inherits = "dev"
panic = "abort"
lto = true
opt-level = "s"

[profile.release-arduino]
inherits = "release"
panic = "abort"
lto = true
opt-level = "s"