[alias]
arduino = "run --bin arduino_script -Z build-std=core --target avr-atmega328p.json --profile release-arduino"

[target.'cfg(target_arch = "avr")']
runner = "ravedude uno -cb 57600 -P /dev/ttyACM0"